# Site settings
title: The Lilly's Blog
url: "//lilia-simeonova.github.io/"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/thelillysblog" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: >
  The personal blog of Lilia Simeonova.

# Your information
# email: your_email@example.com
author: Lilia Simeonova
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: One sentence introducing yourself.
# twitter_username: @lili_vs
# github_username:  lilia-simeonova
# linkedin_username: Lilia Simeonova
# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /:year/:month/:day/:title/
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
